import pandas as pd
import numpy as np
df = pd.read_excel('Veri.xlsx', sheet_name='Veri')
df['Toplam'] = df['Tarım'] + df['Sınai'] + df['Hizmetler']
df['Tarım_%'] = (df['Tarım'] / df['Toplam'] * 100).round(2)
df['Sınai_%'] = (df['Sınai'] / df['Toplam'] * 100).round(2)
df['Hizmetler_%'] = (df['Hizmetler'] / df['Toplam'] * 100).round(2)
print("=" * 60)
print("TEMEL İSTATİSTİKLER (Milyon USD)")
print("=" * 60)
print(df[['Tarım', 'Sınai', 'Hizmetler', 'Toplam']].describe().round(1).to_string())
print("\n" + "=" * 60)
print("YILLIK TOPLAM YATIRIM STOKU")
print("=" * 60)
print(df[['Tarih', 'Tarım', 'Sınai', 'Hizmetler', 'Toplam']].to_string(index=False))
print("\n" + "=" * 60)
print("SEKTÖR PAYLARI (%)")
print("=" * 60)
print(df[['Tarih', 'Tarım_%', 'Sınai_%', 'Hizmetler_%']].to_string(index=False))
df['Toplam_Büyüme_%'] = df['Toplam'].pct_change()*100
print("\n" + "=" * 60)
print("TOPLAM YATIRIM YILLIK BÜYÜME ORANLARI (%)")
print("=" * 60)
print(df[['Tarih', 'Toplam', 'Toplam_Büyüme_%']].to_string(index=False))
print("\n" + "=" * 60)
print("DİKKAT ÇEKEN YILLAR")
print("=" * 60)
print(f"En yüksek toplam yatırım: {df.loc[df['Toplam'].idxmax(), 'Tarih']} → {df['Toplam'].max():,} Mn USD")
print(f"En düşük toplam yatırım: {df.loc[df['Toplam'].idxmin(), 'Tarih']} → {df['Toplam'].min():,} Mn USD")
print(f"En yüksek büyüme yılı: {df.loc[df['Toplam_Büyüme_%'].idxmax(), 'Tarih']} → %{df['Toplam_Büyüme_%'].max():.1f}")
print(f"En düşük büyüme yılı: {df.loc[df['Toplam_Büyüme_%'].idxmin(), 'Tarih']} → %{df['Toplam_Büyüme_%'].min():.1f}")